project/VocaMvc/Models/ErrorViewModel.cs
using System;

namespace VocaMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

project/VocaMvc/Models/Voca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace VocaMvc.Models
{
    public class Voca
    {
        public int Id { get; set; }
        [Display(Name = " ")]
        public string Word { get; set; }
        [Display(Name = " ")]
        public string Meaning { get; set; }
        [Display(Name = " ")]
        public DateTime EnrollmentDate { get; set; }
        [Display(Name = " ")]
        public DateTime EditDate { get; set; }

        public Voca()
        {
            EnrollmentDate = DateTime.UtcNow;
            TimeZoneInfo cstZone = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");
            DateTime cstTime = TimeZoneInfo.ConvertTimeFromUtc(EnrollmentDate, cstZone);
            this.EnrollmentDate = cstTime;

        }



    }
}

project/VocaMvc/Controllers/VocaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VocaMvc.Models;

namespace VocaMvc.Controllers
{
    public class VocaController : Controller
    {
        public ActionResult Index()
        {
            IEnumerable<Voca> voca;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("vocas").Result;
            voca = response.Content.ReadAsAsync<IEnumerable<Voca>>().Result;
            return View(voca);

        }


        public ActionResult AddOrEdit(int id=0) {

            if (id == 0)
                return View(new Voca());
            else 
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("vocas/"+id.ToString()).Result;
                return View(response.Content.ReadAsAsync<Voca>().Result);
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Voca voc) {
            if (voc.Id == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("vocas", voc).Result;
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("vocas/"+voc.Id,voc).Result;
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteConfirm(int id)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("vocas/" + id.ToString()).Result;
            return View(response.Content.ReadAsAsync<Voca>().Result);

        }

        public ActionResult Delete(int id) {

            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("vocas/" + id.ToString()).Result;
            return RedirectToAction("Index");
        }
    }
}

project/VocaMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

project/VocaMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VocaMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Voca" asp-action="Index">VocaMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voca" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - VocaMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

project/VocaMvc/Views/Voca/AddOrEdit.cshtml
@model VocaMvc.Models.Voca



@if (@Model.Id == 0)
{
    ViewData["Title"] = "単語帳-追加";
    <h1 style="background-color:#e65100; color:white; font-weight:500;width:645px;">単語帳-追加</h1>
    <br>
}
else
{
    ViewData["Title"] = "単語帳-更新";
    <h1 style="background-color:#e65100; color:white; font-weight:500;width:645px;">単語帳-更新</h1>
    <br>
}

<form asp-action="AddOrEdit" id="addOrEdit" onsubmit="return validate();">
    <div class="form-body" style="line-height:0;">

        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)


            <div class="form-group">
                <label asp-for="Word" class="control-label"></label>
                <input asp-for="Word" id="word" name="word" class="form-control" style="width:250px;" placeholder="単語" />
                <span asp-validation-for="Word" class="text-danger"></span>
            </div>



            @if (@Model.Id == 0)
            {
                <div class="form-group" style="display:none">
                    <label asp-for="EnrollmentDate" class="control-label"></label>
                    @Html.TextBox("EnrollmentDate", DateTime.Now, new { @readonly = "readonly", @style = "border: none;" })
                </div>
                <div class="form-group" style="display:none">
                    <label asp-for="EditDate" class="control-label"></label>
                    更新日: @Html.TextBox("EditDate", DateTime.Now, new { @readonly = "readonly", @style = "border: none;" })
                    <span asp-validation-for="EditDate" class="text-danger"></span>
                </div>
            }
            else
            {
                <div class="form-group">
                    <label asp-for="EnrollmentDate" class="control-label"></label><br>
                    作成日:@Html.TextBox("EnrollmentDate", Model.EnrollmentDate, new { @readonly = "readonly", @style = "border: none;" })
                    <br>
                    更新日: @Html.TextBox("EditDate", DateTime.Now, new { @readonly = "readonly", @style = "border: none; margin-bottom:0;" })
                    <span asp-validation-for="EditDate" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <input asp-for="Meaning" id="meaning" class="form-control" style="width:500px;" placeholder="意味" />
                <br>
                <span asp-validation-for="Meaning" id="meaningCounter" class="text-danger" style="position:relative; bottom:-9px; left:437px"></span>
            </div>

            <div class="form-group" style="float:left;">
                <a asp-action="Index" class="btn btn-primary" style="display: block; border:0; outline:0;background-color: #BDBDBD; width:70px;position: relative; left:491px;">戻る</a>

            </div>
            <div class="form-group" style="float:left;">
                <input type="submit" value="確定" class="btn btn-primary" style="display: block; border:0; outline:0;background-color: #f33513; width:70px;position: relative; left:506px;" />
            </div>

        }

    </div>
</form>
<script>
    var word = document.getElementById('word');
    var meaning = document.getElementById('meaning');



    function validate() {

        if (word.value == '') {
            alert('please enter word!')
            return false
        }

            if (meaning.value == '') {
                alert('please enter meaning!')
                return false
            }


        }
</script>


@section scripts{
    <script>


        $(function () {
            $('#meaning').keyup(function (e) {
                var content = $(this).val();
                $(this).height(((content.split('\n').length + 1) * 1.5) + 'em');
                $('#meaningCounter').html(content.length + '/300');
            });
            $('#meaning').keyup();
        });


        $('#word').on('keyup', function () {

            if ($(this).val().length > 50) {

                alert("50字以上入力できません。");

                $(this).val($(this).val().substring(0, 50));

            }

        });

        $('#meaning').on('keyup', function () {

            if ($(this).val().length > 300) {

                alert("300字以上入力できません。");

                $(this).val($(this).val().substring(0, 300));

            }

        });
    </script>

}

project/VocaMvc/Views/Voca/DeleteConfirm.cshtml
@model VocaMvc.Models.Voca

@{
    ViewData["Title"] = "Delete";
}

<h1 style="background-color:#e65100; color:white; font-weight:500;width:645px;">単語帳-削除</h1>

<div>

    <dl class="row">

        <dd class="col-sm-10" style="display:none">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dd class="col-sm-10">
            <h1> @Html.DisplayFor(model => model.Word)</h1>
        </dd>


        <dd class="col-sm-10">
            作成日: @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>

        <dd class="col-sm-10">
            更新日: @Html.DisplayFor(model => model.EditDate)
        </dd>


        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meaning)
        </dd>
    </dl>

</div>

<div class="form-group" style="float:left;">
    <a asp-action="Index" class="btn btn-primary" style="display: block; border:0; outline:0;background-color: #BDBDBD; width:70px;position: relative; left:491px;">戻る</a>
</div>
<div class="form-group" style="float:left;">
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-primary" style="display: block; border:0; outline:0;background-color: #f33513; width:70px;position: relative; left:506px;">確定</a>
</div>

project/VocaMvc/Views/Voca/Index.cshtml
@model IEnumerable<VocaMvc.Models.Voca>

@{
    ViewData["Title"] = "単語帳";
}

@*<h1>単語帳</h1>*@
<h1 style="background-color:#e65100; color:white; font-weight:500; width:645px;">単語帳</h1>

@foreach (var item in Model)
{
    <div>
        <div style="display:none">
            @Html.DisplayFor(modelItem => item.Id)
        </div>
        <h1>
            @Html.DisplayFor(modelItem => item.Word)
        </h1>

        <div>
            作成日: @Html.DisplayFor(modelItem => item.EnrollmentDate)
        </div>

        <div>
            更新日: @Html.DisplayFor(modelItem => item.EditDate)
        </div>
        <br>
        <div>
            @Html.DisplayFor(modelItem => item.Meaning)
        </div>
        <br>


        <div style="margin:-58px;">
            <a asp-action="DeleteConfirm" asp-route-id="@item.Id" class="btn btn-primary" style="display: block; border:0; outline:0; background-color: #e65100; width:70px;position: relative; left:634px;bottom:100px;">削除</a>
            <br>
            <a asp-action="AddOrEdit" asp-route-id="@item.Id" class="btn btn-primary" style="display: block; border:0; outline:0; background-color: #e65100; width:70px;position: relative; left:634px;bottom:110px;">更新</a>
        </div>
    </div>
    <hr />
}
<br>
<p>
    <a href="@Url.Action("AddOrEdit","Voca")" class="btn-danger" style="display: block; background-color: #e65100; height:48px; width: 645px; text-align:center;font-weight:500;font-size:30px;">+</a>
</p>